-- CreateTable
CREATE TABLE "StoreSettings" (
    "id" TEXT NOT NULL,
    "storeName" TEXT NOT NULL DEFAULT 'Khali''s Beauty Store',
    "storeEmail" TEXT NOT NULL DEFAULT 'admin@khalisbeauty.com',
    "storePhone" TEXT NOT NULL DEFAULT '+880 1712-345678',
    "storeAddress" TEXT NOT NULL DEFAULT 'Dhaka, Bangladesh',
    "currency" TEXT NOT NULL DEFAULT 'BDT',
    "timezone" TEXT NOT NULL DEFAULT 'Asia/Dhaka',
    "emailNotifications" BOOLEAN NOT NULL DEFAULT true,
    "orderNotifications" BOOLEAN NOT NULL DEFAULT true,
    "stockAlerts" BOOLEAN NOT NULL DEFAULT true,
    "promotionalEmails" BOOLEAN NOT NULL DEFAULT false,
    "twoFactorAuth" BOOLEAN NOT NULL DEFAULT false,
    "loginAlerts" BOOLEAN NOT NULL DEFAULT true,
    "sessionTimeout" INTEGER NOT NULL DEFAULT 30,
    "freeShippingThreshold" DOUBLE PRECISION NOT NULL DEFAULT 500,
    "standardShippingFee" DOUBLE PRECISION NOT NULL DEFAULT 60,
    "expressShippingFee" DOUBLE PRECISION NOT NULL DEFAULT 120,
    "cashOnDelivery" BOOLEAN NOT NULL DEFAULT true,
    "bkashEnabled" BOOLEAN NOT NULL DEFAULT false,
    "nagadEnabled" BOOLEAN NOT NULL DEFAULT false,
    "cardPaymentEnabled" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "StoreSettings_pkey" PRIMARY KEY ("id")
);

-- Insert default settings
INSERT INTO "StoreSettings" (
    "id",
    "storeName",
    "storeEmail",
    "storePhone",
    "storeAddress",
    "currency",
    "timezone",
    "emailNotifications",
    "orderNotifications",
    "stockAlerts",
    "promotionalEmails",
    "twoFactorAuth",
    "loginAlerts",
    "sessionTimeout",
    "freeShippingThreshold",
    "standardShippingFee",
    "expressShippingFee",
    "cashOnDelivery",
    "bkashEnabled",
    "nagadEnabled",
    "cardPaymentEnabled",
    "createdAt",
    "updatedAt"
) VALUES (
    '00000000-0000-0000-0000-000000000001',
    'Khali''s Beauty Store',
    'admin@khalisbeauty.com',
    '+880 1712-345678',
    'Dhaka, Bangladesh',
    'BDT',
    'Asia/Dhaka',
    true,
    true,
    true,
    false,
    false,
    true,
    30,
    500,
    60,
    120,
    true,
    false,
    false,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);
